# SPDX-License-Identifier: Apache-2.0
"""Meridian V1 Usage plugin public interface."""

from ._version import __version__
from .aggregation import (
    AggregationRunner,
    AggregationRunResult,
    AggregationSpec,
    aggregate_events,
)
from .correlation import UsageCorrelation
from .errors import (
    CheckpointConflict,
    ClaimUnavailable,
    DecimalOverflow,
    DimensionViolation,
    InactiveMeter,
    InvalidCorrection,
    InvalidUsage,
    InvalidUsageResult,
    UnitMismatch,
    UnknownMeter,
    UsageConflict,
)
from .models import (
    DimensionSpec,
    MeterV1,
    UnitTransform,
    UsageAggregate,
    UsageAggregateV1,
    UsageEvent,
    UsageEventV1,
    UsageScope,
    UsageWindow,
    event_set_fingerprint,
)
from .plugin import Usage, UsagePluginFactory
from .query import UsageOrder, UsageQueries, UsageQuery, UsageQueryResult
from .repository import (
    AggregationClaim,
    BatchItemResult,
    BatchMode,
    BatchReceipt,
    RecordReceipt,
    RecordStatus,
    UsageCheckpoint,
    UsageRecorder,
    UsageRepository,
    UsageResources,
)
from .retention import RetentionInput
from .schema import (
    UsageSchemaProvider,
    aggregate_schema,
    batch_schema,
    checkpoint_schema,
    claim_schema,
    event_schema,
    meter_schema,
    usage_schemas,
)

__all__ = [
    "AggregationClaim",
    "AggregationRunResult",
    "AggregationRunner",
    "AggregationSpec",
    "BatchItemResult",
    "BatchMode",
    "BatchReceipt",
    "CheckpointConflict",
    "ClaimUnavailable",
    "DecimalOverflow",
    "DimensionSpec",
    "DimensionViolation",
    "InactiveMeter",
    "InvalidCorrection",
    "InvalidUsage",
    "InvalidUsageResult",
    "MeterV1",
    "RecordReceipt",
    "RecordStatus",
    "RetentionInput",
    "UnitMismatch",
    "UnitTransform",
    "UnknownMeter",
    "Usage",
    "UsageAggregate",
    "UsageAggregateV1",
    "UsageCheckpoint",
    "UsageConflict",
    "UsageCorrelation",
    "UsageEvent",
    "UsageEventV1",
    "UsageOrder",
    "UsagePluginFactory",
    "UsageQueries",
    "UsageQuery",
    "UsageQueryResult",
    "UsageRecorder",
    "UsageRepository",
    "UsageResources",
    "UsageSchemaProvider",
    "UsageScope",
    "UsageWindow",
    "__version__",
    "aggregate_events",
    "aggregate_schema",
    "batch_schema",
    "checkpoint_schema",
    "claim_schema",
    "event_schema",
    "event_set_fingerprint",
    "meter_schema",
    "usage_schemas",
]
